name: Deploy Project
on:
  push:
    branches:
      - 'releases/**'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.scrpt-filename }}
    steps:
      - name: Download the Code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Publish JS FileName
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'scrpt-filename={}' >> $GITHUB_OUTPUT ';'
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-report
          path: dist

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
      - name: Output Filename
        run:  echo " {{needs.build.outputs.script-file }}"




